sudo: required
services:
    - docker

before_install:
    - docker build -t sahil1/docker_sg_frontend -f Dockerfile.dev .

script:
    - docker run sahil1/docker_sg_frontend npm run test -- --coverage
