#docker build -f Dockerfile.dev .
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 572841d4ba27
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm","run","start"]
